/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  docsSidebar: [
    { id: 'intro', label: 'Introducción', type: 'doc' },
    { id: 'preparacion', label: 'Preparación', type: 'doc' },
    {
      type: 'category',
      label: 'Configuración',
      items: [
        { id: 'setup/entorno-local', label: 'Entorno local', type: 'doc' },
        {
          type: 'category',
          label: 'Herramientas',
          items: [
            { id: 'setup/editor-config', label: 'Editores', type: 'doc' },
            { id: 'setup/eslint', label: 'Linters', type: 'doc' },
            { id: 'setup/prettier', label: 'Formateadores', type: 'doc' },
          ]
        },
        {
          type: 'category',
          label: 'Proyectos',
          items: [
            { id: 'projects/react', label: 'React.js', type: 'doc' },
            { id: 'projects/nodejs', label: 'Node.js', type: 'doc' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tecnologías',
      items: [
        {
          type: 'category',
          label: 'Git',
          items: [
            'git/README',
            'git/instalacion-configuracion',
            'git/conceptos-comandos-esenciales',
            'git/gitignore',
            { id: 'git/ramas', label: 'Ramas', type: 'doc'  },
            'git/repositorios-remotos',
            { id: 'git/etiquetas', label: 'Etiquetas', type: 'doc'  },
            'git/reescribiendo-la-historia',
            { id: 'git/stashing', label: 'Stashing', type: 'doc'  },
            'git/github',
            { id: 'git/llaves-ssh', label: 'Configurar tu llave SSH', type: 'doc'  },
          ],
        },
        {
          type: 'category',
          label: 'HTML y CSS',
          items: [
            'html-y-css/introduccion-a-html',
            'html-y-css/introduccion-a-css',
            'html-y-css/mas-elementos-de-html',
            'html-y-css/tablas',
            'html-y-css/formularios',
            'html-y-css/el-modelo-de-caja-en-css',
            'html-y-css/fondos-backgrounds',
            'html-y-css/posicionamiento',
            'html-y-css/selectores-css',
            'html-y-css/bordes-sombras-y-gradientes',
            'html-y-css/media-queries',
            'html-y-css/unidades',
            'html-y-css/flexbox',
          ],
        },
        {
          type: 'category',
          label: 'JavaScript',
          items: [
            {
              type: 'category',
              label: 'Fundamentos',
              items: [
                { id: 'javascript/README', label: 'Introducción', type: 'doc' },
                'javascript/primeros-pasos',
                'javascript/tipos-y-operadores',
                'javascript/variables',
                'javascript/condicionales',
                'javascript/ciclos',
                'javascript/arreglos',
                'javascript/mas-cadenas-de-texto',
                'javascript/funciones',
                'javascript/objetos-literales',
              ]
            },
            {
              type: 'category',
              label: 'Avanzado',
              items: [
                'javascript/avanzado/prototipos',
                { id: 'javascript/avanzado/librerias-node.js', label: 'Librerías Node.js', type: 'doc' },
                'javascript/avanzado/es6',
                'javascript/avanzado/uso-this',
                'javascript/avanzado/programacion-funcional',
                'javascript/avanzado/scope-hoisting-closures',
                'javascript/avanzado/programacion-asincronica',
                'javascript/avanzado/excepciones',
                'javascript/avanzado/testing',
              ]
            },
            {
              type: 'category',
              label: 'Navegador',
              items: [
                { id: 'javascript/navegador/README', label: 'Introducción', type: 'doc' },
                'javascript/navegador/primeros-pasos',
                'javascript/navegador/manipulando-html',
                'javascript/navegador/escuchando-eventos',
                'javascript/navegador/local-storage',
                'javascript/navegador/history',
                'javascript/navegador/canvas',
                'javascript/navegador/notificaciones',
                'javascript/navegador/video-audio',
                'javascript/navegador/drag-drop',
                'javascript/navegador/json',
                'javascript/navegador/peticiones-http',
              ]
            },
          ],
        },
        {
          type: 'category',
          label: 'React',
          items: [
            {
              type: 'category',
              label: 'Fundamentos',
              items: [
                { id: 'react/README', label: 'Introducción', type: 'doc' },
                'react/primeros-pasos',
                'react/jsx',
                'react/componentes',
                'react/mas-sobre-estado',
                'react/formularios',
                'react/peticiones-http-con-axios',
                'react/react-hooks',
                'react/react-router',
                'react/estructura-carpetas',
                'react/context',
                'react/carga-de-imagenes',
                'react/react-bootstrap',
                'react/testing',
                'react/componentes-clase',
              ]
            },
            {
              type: 'category',
              label: 'Redux',
              items: [
                { id: 'redux/README', label: 'Introducción', type: 'doc' },
                'redux/primeros-pasos',
                'redux/action-creators',
                'redux/react-redux',
                'redux/middlewares',
                'redux/redux-thunk',
                'redux/combinando-reductoras',
                'redux/redux-tool-kit',
                'redux/testing',
              ]
            },
          ],
        },
        {
          type: 'category',
          label: 'Node.js',
          items: [
            'nodejs/README',
            'nodejs/instalacion',
            'nodejs/manipulacion-de-archivos',
            {
              type: 'category',
              label: 'Express.js',
              items: [
                {
                  type: 'category',
                  label: 'Fundamentos',
                  items: [
                    { id: 'nodejs/express/README', label: 'Introducción', type: 'doc' },
                    'nodejs/express/primeros-pasos',
                    'nodejs/express/el-protocolo-http',
                    'nodejs/express/rutas',
                    'nodejs/express/vistas',
                    'nodejs/express/middlewares-y-manejo-de-errores',
                    'nodejs/express/formularios',
                    'nodejs/express/cookies-y-sesion',
                  ]
                },
                {
                  type: 'category',
                  label: 'Avanzado',
                  items: [
                    'nodejs/express/avanzado/web-api',
                    'nodejs/express/avanzado/autenticacion',
                    'nodejs/express/avanzado/envio-de-correos',
                    'nodejs/express/avanzado/carga-de-imagenes',
                    'nodejs/express/avanzado/mongoose',
                    'nodejs/express/avanzado/testing',
                    'nodejs/express/avanzado/deployment',
                    'nodejs/express/avanzado/web-sockets',
                  ]
                },
              ]
            },
          ],
        },
        {
          type: 'category',
          label: 'Algoritmos',
          items: [
            { id: 'algoritmos/README', label: 'Introducción', type: 'doc' },
            'algoritmos/describiendo-algoritmos',
            'algoritmos/complejidad',
            'algoritmos/estructuras-de-datos',
            'algoritmos/recursion',
            'algoritmos/ordenamiento',
            'algoritmos/busqueda',
            'algoritmos/programacion-dinamica',
          ],
        },
        {
          type: 'category',
          label: 'Bases de datos',
          items: [
            { id: 'bases-de-datos/README', label: 'Introducción', type: 'doc'},
            'bases-de-datos/bases-de-datos-relacionales',
            'bases-de-datos/sql',
            'bases-de-datos/ddl',
            'bases-de-datos/mongodb',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;

//ssh keys de git
