// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // tutorialSidebar: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: 'Preparación',
  //     items: [
  //       'preparacion/conceptos-basicos',
  //       'preparacion/el-editor-de-texto',
  //       'preparacion/la-linea-de-comandos',
  //       'preparacion/git-y-github',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Git',
  //     items: [
  //       'git/intro',
  //       'git/instalacion-configuracion',
  //       'git/conceptos-comandos-esenciales',
  //     ],
  //   },
  // ],
};

module.exports = sidebars;
