/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  docsSidebar: [
    { id: 'intro', label: 'Acuerdos', type: 'doc' },
    {
      type: 'category',
      label: 'Configuración',
      collapsible: false,
      items: [
        { id: 'setup/entorno-local', label: 'Entorno local', type: 'doc' },
        {
          type: 'category',
          label: 'Herramientas',
          items: [
            { id: 'setup/editor-config', label: 'Editores', type: 'doc' },
            { id: 'setup/eslint', label: 'Linters', type: 'doc' },
            { id: 'setup/prettier', label: 'Formateadores', type: 'doc' },
          ]
        },
        {
          type: 'category',
          label: 'Proyectos',
          collapsible: false,
          items: [
            { id: 'projects/react', label: 'React.js', type: 'doc' },
            { id: 'projects/nodejs', label: 'Node.js', type: 'doc' },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
